image: docker:stable  # Use the official Docker image as the runner

stages:
  - build
  - deploy

variables:
  IMAGE_NAME: srvraj311/health-io-api  # Replace with your Docker Hub details
  IMAGE_TAG: latest #$CI_COMMIT_TAG  # Use the Git tag for the image tag
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION

build:
  image: docker:20.10.16
  stage: build
  variables:
    SECURE_FILES_DOWNLOAD_PATH: '.secure_files/health-io-api-key.pem'
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD  # Login to Docker Hub (securely store credentials using GitLab CI/CD variables)
    - docker build --progress=plain -t $IMAGE_NAME .
    - docker push $IMAGE_NAME:$IMAGE_TAG
# Target EC2 Instance

deploy:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  stage: deploy
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    - apk add --no-cache --upgrade bash
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - ls -lah .secure_files
    - chmod 600 $SSH_PRIVATE_KEY_PATH
    - scp -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY_PATH docker-deploy.sh ec2-user@34.224.222.50:/tmp/docker-deploy.sh  # Securely transfer deployment script
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY_PATH ec2-user@34.224.222.50 'bash /tmp/docker-deploy.sh '$IMAGE_NAME' '$IMAGE_TAG''  # Execute deployment script on EC2
