image: docker:stable  # Use the official Docker image as the runner

stages:
  - build
  - deploy

variables:
  IMAGE_NAME: srvraj311/health-io-api  # Replace with your Docker Hub details
  IMAGE_TAG: latest #$CI_COMMIT_TAG  # Use the Git tag for the image tag
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION

build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD  # Login to Docker Hub (securely store credentials using GitLab CI/CD variables)
    - docker build --progress=plain -t $IMAGE_NAME .
    - docker push $IMAGE_NAME:$IMAGE_TAG
# Target EC2 Instance

deploy:
  stage: deploy
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker pull $IMAGE_NAME:$IMAGE_TAG
    - echo "Loading deployment configuration..."
    - deployment_config=$(cat ci/cd/config.yaml)